### ISSUE TITLE
There already is a “doxie”

### ISSUE THREAD

**Issue by tomek-he-him** [studio-b12/doxie#4]
http://www.getdoxie.com/

@stoeffel should we care?

**Comment by stoeffel** [comment]
Hmmm... I don't think that we have to care :smile:

**Comment by tomek-he-him** [comment]
It might just be hard to get near the top in [search results](https://startpage.com/do/search?query=doxie). But I guess you’re right. If it’s not a problem [for gulp](http://gulp.com), there’s no need to worry for us.
